/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1b1d0e",
        "surface-bright": "#393939",
        "on-error": "#690005",
        "on-secondary-container": "#b9baa3",
        "primary-container": "#ffbf00",
        "tertiary": "#e8e5e4",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "secondary-container": "#494a38",
        "on-tertiary-fixed-variant": "#474746",
        "surface-container-low": "#1c1b1b",
        "on-primary-fixed-variant": "#5c4300",
        "surface": "#131313",
        "on-secondary-fixed-variant": "#474836",
        "surface-container-high": "#2a2a2a",
        "outline": "#9c8f78",
        "surface-container": "#201f1f",
        "on-secondary": "#303221",
        "tertiary-container": "#cbc9c8",
        "surface-dim": "#131313",
        "secondary-fixed-dim": "#c8c8b0",
        "outline-variant": "#504532",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-highest": "#353534",
        "on-tertiary-fixed": "#1b1b1c",
        "primary-fixed": "#ffdfa0",
        "inverse-primary": "#795900",
        "on-tertiary-container": "#555454",
        "error-container": "#93000a",
        "on-surface-variant": "#d4c5ab",
        "on-primary-fixed": "#261a00",
        "tertiary-fixed-dim": "#c8c6c5",
        "background": "#131313",
        "primary": "#ffe2ab",
        "on-surface": "#e5e2e1",
        "secondary-fixed": "#e4e4cc",
        "on-primary-container": "#6d5000",
        "primary-fixed-dim": "#fbbc00",
        "inverse-surface": "#e5e2e1",
        "secondary": "#c8c8b0",
        "on-primary": "#402d00",
        "inverse-on-surface": "#313030",
        "surface-tint": "#fbbc00",
        "tertiary-fixed": "#e5e2e1",
        "on-tertiary": "#303030",
        "on-background": "#e5e2e1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem"
      },
      spacing: {
        "stack-sm": "12px",
        "stack-md": "24px",
        "gutter": "16px",
        "stack-lg": "48px",
        "container-padding": "24px",
        "base": "8px",
        "safe": "env(safe-area-inset-bottom)"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "34px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
